export const jackets = [
  //Female
  {
    name: "Brown coat",
    color:"brown",
    price:"150.00$",
    onSale:false,
    desc: "A warm brown coat",
    img:"../images/brown-jacket.jpg",
    gender: "female",
    highlight: false,
    id: 1,
    main: true
  },
  {
    name: "Another brown coat",
    color:"brown",
    price:"200.00$",
    onSale:false,
    desc: "Another warm brown coat",
    img:"../images/another-brown.jpg",
    gender: "female",
    highlight: false,
    id: 2,
    main: true
  },
  {
    name: "yellow coat",
    color:"yellow",
    price:"150.00$",
    onSale:false,
    desc: "A yellow rain coat",
    img:"../images/yellow-coat_oppdatert.jpg",
    gender: "female",
    highlight: true,
    id: 3,
    main: true
  },
  {
    name: "black jacket",
    color:"black",
    price:"200.00$",
    onSale:false,
    desc: "A nice black jacket",
    img:"../images/black-jacket_oppdatert.jpg",
    gender: "female",
    highlight: true,
    id: 4,
    main: true
  },
  {
    name: "colorful coat",
    color:"many",
    price:"170.00$",
    onSale:false,
    desc: "A colorful coat for cold days",
    img:"../images/colorful-jacket.jpg",
    gender: "female",
    highlight: false,
    id: 5,
    main: false
  },
  {
    name: "red coat",
    color:"red",
    price:"150.00$",
    onSale:false,
    desc: "A red coat",
    img:"../images/red-coar.jpg",
    gender: "female",
    highlight: false,
    id: 6,
    main: false
  },
  {
    name: "white jacket",
    color:"white",
    price:"170.00$",
    onSale:false,
    desc: "A white jacket",
    img:"../images/white-jacket_oppdatert.jpg",
    gender: "female",
    highlight: true,
    id: 7,
    main: false
  },
  {
    name: "yellow rain jacket",
    color:"yellow",
    price:"150.00$",
    onSale:false,
    desc: "A yellow jacket that keeps yo dry in the rain",
    img:"../images/yellow-rain_oppdatert.jpg",
    gender: "female",
    highlight: true,
    id: 8,
    main: false
  },
  //Male
  {
    name: "casual jacket",
    color:"light brown",
    price:"200.00$",
    onSale:false,
    desc: "A nice jacket for casual occations",
    img:"../images/casual-jacket_oppdatert.jpg",
    gender: "male",
    highlight: true,
    id: 9,
    main: true
  },  {
    name: "hiking jacket",
    color:"black",
    price:"170.00$",
    onSale:false,
    desc: "A good jacket for outdoors things",
    img:"../images/hiking-jacket_oppdatert.jpg",
    gender: "male",
    highlight: true,
    id: 10,
    main: true
  },{
    name: "dark jacket",
    color:"black",
    price:"200.00$",
    onSale:false,
    desc: "A black jacket",
    img:"../images/black-jakcet.jpg",
    gender: "male",
    highlight: false,
    id: 11,
    main: true
  },{
    name: "yellow jacket",
    color:"yellow",
    price:"170.00$",
    onSale:false,
    desc: "A yellow rain jacket",
    img:"../images/yeallow-jacket.jpg",
    gender: "male",
    highlight: false,
    id: 12,
    main: true
  },{
    name: "lumber jack jacket",
    color:"many",
    price:"100.00$",
    onSale:false,
    desc: "A jacket for doing stuff",
    img:"../images/lumber-jack_oppdatert.jpg",
    gender: "male",
    highlight: false,
    id: 13,
    main: false
  },{
    name: "warm jacket",
    color:"black",
    price:"150.00$",
    onSale:false,
    desc: "A black warm jacket",
    img:"../images/warm-jacket_oppdatert.jpg",
    gender: "male",
    highlight: false,
    id: 14,
    main: false
  },{
    name: "brown jacket",
    color:"brown",
    price:"100.00$",
    onSale:false,
    desc: "A brown jacket",
    img:"../images/brown.jpg",
    gender: "male",
    highlight: false,
    id: 15,
    main: false
  },{
    name: "warm coat",
    color:"light brown",
    price:"150.00$",
    onSale:false,
    desc: "A warm coat",
    img:"../images/warm-coat.jpg",
    gender: "male",
    highlight: false,
    id: 16,
    main: false
  },
]